export enum SessionStatus {
    ACTIVE = 'ACTIVE',
    AWAITING_CLOSURE_CONFIRMATION = 'AWAITING_CLOSURE_CONFIRMATION',
    CLOSED_BY_USER = 'CLOSED_BY_USER',
    CLOSED_BY_TIMEOUT = 'CLOSED_BY_TIMEOUT',
}
